//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curUser
    {
        public int ID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int idstate { get; set; }
    
        public virtual curCstate curCstate { get; set; }
        public virtual curUser curUser1 { get; set; }
        public virtual curUser curUser2 { get; set; }
    }
}
